### ISSUE TITLE
Multiple dex files define Lcom/google/android/gms/common/internal/zzbb

### ISSUE THREAD

**Issue by peace2knowledge** [theankurkedia/newsbuzz#2]
Launching lib\main.dart on MI 6 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/common/internal/zzbb;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Finished with error: Gradle build failed: 1

**Comment by theankurkedia** [comment]
It the problem with firebase dependencies, I specifically used the dependencies' version used [here](https://github.com/flutter/friendlychat-steps/blob/master/full_steps/step_1_set_up_firebase/pubspec.yaml)

**Comment by peace2knowledge** [comment]
what shoud I do

**Comment by theankurkedia** [comment]
@peace2knowledge just change the dependencies in pubspec.yaml to exact same version which are used here.

**Comment by peace2knowledge** [comment]
I am from china，Android phone did not install google service framework。I did install framework，but log show:

Running "flutter packages get" in newsbuzz...
Launching lib\main.dart on MI 6 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build\app\outputs\apk\app-debug.apk (24.6MB).
Installing build\app\outputs\apk\app.apk...

**do not  compelete**

**Comment by theankurkedia** [comment]
@peace2knowledge Please go thought readme once, It happens when firebase is not properly configured with the app.

**Comment by daraouk** [comment]
@theankurkedia I'm getting the same issue and went through the README twice...
