### ISSUE TITLE
Built  cant compelete,

### ISSUE THREAD

**Issue by peace2knowledge** [theankurkedia/newsbuzz#3]
Launching lib\main.dart on MI 6 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build\app\outputs\apk\app-debug.apk (24.6MB).

@theankurkedia  I want to install newsbuzz on my phone, and review code. but always can't complete

**Comment by theankurkedia** [comment]
Pull the latest master branch, follow updated instructions in Readme.md. Please close the issue if it is resolved.

**Comment by peace2knowledge** [comment]
@theankurkedia thank you,  it works
