### ISSUE TITLE
logo/icon proposal

### ISSUE THREAD

**Issue by jbeguna04** [theankurkedia/newsbuzz#5]
Hi good day! Im Jibbie Eguna, a graphics designer, I would like to ask for your permission to propose a new designs of logo in your application/project. I would like to help projects in open-source .I would just like to propose new designs. Hoping for your positive response Thank You!

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/39759414-3431c66e-5305-11e8-9fec-b05e4dac4c57.png)
Here are my proposed designs. Im open to any suggestions. Thank You

**Comment by theankurkedia** [comment]
@jbeguna04 Hi. The logo you have designed looks good, we can add it to the app.

**Comment by jbeguna04** [comment]
thank you, can i make a pull request?

**Comment by theankurkedia** [comment]
Yeah sure.

**Comment by jbeguna04** [comment]
ill be making a PR now. Thank you for waiting

**Comment by jbeguna04** [comment]
already created PR hope that you can visit it. Thank You
